version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - run: yarn
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true
      - run: .circleci/build.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
