version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.3
    steps:
      - checkout
      - run: yarn
      - run: yarn coverage
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true
      - run: .circleci/build.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - docker.com
          filters:
            branches:
              ignore: /dependabot.*/
            tags:
              only: /.*/
